g = int(input())
c = int(input())
e = int(input())
p = int(input())
l = int(input())
s = int(input())

ginger = (f"Ginger {g*240}")
print (ginger)
chamomile = (f"Chamomile {c*240}")
print (chamomile)
earlgray = (f"Earl Gray {e*240}")
print (earlgray)
peppermint = (f"Peppermint {p*240}")
print (peppermint)
Lemon = (f"Lemon {l*240}")
print (Lemon)
Strawberry = (f"Strawberry {s*240}")
print (Strawberry)
